spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres

  jpa:
    generate-ddl: true

  liquibase:
    change-log: classpath:db/changelog.xml
